apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - services.yaml
  - deployments.yaml
  - postgres.yaml

images:
  - name: ghcr.io/your-org/ticket-management-frontend
    newName: infra-frontend
    newTag: latest
  - name: ghcr.io/your-org/ticket-management-backend-py
    newName: infra-backend-py
    newTag: latest
  - name: ghcr.io/your-org/ticket-management-ml
    newName: infra-ml
    newTag: latest
  - name: ghcr.io/your-org/ticket-management-route-go
    newName: infra-route-go
    newTag: latest

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent